; Generated by JakAdaC 8086 Compiler
; Assignment 8 - TAC to ASM Code Generator

%include "io.asm"

section .text
global _start

section .data
; No global variables or string literals

; -- ('proc', 'one') --
one:
 push bp
 mov bp, sp
 sub sp, 2
; -- ('=', 'A', '10') --
; -- WARNING: No translation available for = --
; -- ('=', 'B', '40') --
; -- WARNING: No translation available for = --
; -- ('+', '_t1', 'A', 'B') --
; -- WARNING: No translation available for + --
; -- ('=', 'CC', '_t1') --
; -- WARNING: No translation available for = --
; -- ('endp', 'one') --
 mov sp, bp
 pop bp
 ret 0

_start:
 call one
 mov eax, 1    ; Exit syscall number
 xor ebx, ebx  ; Exit code 0
 int 0x80      ; Call kernel
