; Generated by JakAdaC 8086 Compiler
; Assignment 8 - TAC to ASM Code Generator

%include "io.asm"

section .text
global _start

section .data
; No global variables or string literals

; -- ('proc', 'five') --
five:
 push bp
 mov bp, sp
 sub sp, 0
; -- ('proc', 'fun') --
fun:
 push bp
 mov bp, sp
 sub sp, 2
; -- ('*', '_t1', 'ParamA', 'ParamB') --
; -- WARNING: No translation available for * --
; -- ('=', 'LocalC', '_t1') --
; -- WARNING: No translation available for = --
; -- ('endp', 'fun') --
 mov sp, bp
 pop bp
 ret 0
; -- ('=', 'A', '7') --
; -- WARNING: No translation available for = --
; -- ('=', 'B', '6') --
; -- WARNING: No translation available for = --
; -- ('push', 'B') --
 mov ax, B
 push ax
; -- ('push', 'A') --
 mov ax, A
 push ax
; -- ('call', 'fun') --
 call fun
; -- ('endp', 'five') --
 mov sp, bp
 pop bp
 ret 0

_start:
 call five
 mov eax, 1    ; Exit syscall number
 xor ebx, ebx  ; Exit code 0
 int 0x80      ; Call kernel
