procedure test1 is
a,b,c:real;
x,y,z:integer;
begin
end test1;

--    
--    ### Expected Behavior
--    
--    1. **Procedure Declaration ("test1"):**
--       - The procedure `test1` is declared at the global scope (depth 0).  
--       - It has no parameters.  
--       - Its body creates a new scope (depth 1).
--    
--    2. **Local Declarations (Inside test1, Depth 1):**
--       - **For `a, b, c : real;`**
--         - Assuming the type `real` has a size of 4 bytes (as defined in your type sizes), the offsets will be:
--           - `a`: offset 0  
--           - `b`: offset 4  
--           - `c`: offset 8  
--       - **For `x, y, z : integer;`**
--         - Assuming the type `integer` has a size of 2 bytes, the offset continues from the previous declaration:
--           - The current offset after `a, b, c` is 12.
--           - `x`: offset 12  
--           - `y`: offset 14  
--           - `z`: offset 16  
--    
--    3. **Local Size Calculation:**
--       - After declaring all variables, the final offset becomes **18**.  
--       - This value is stored in the procedure's symbol table entry (at depth 0) as its local size.
--    
--    ---
--    
--    ### Expected Symbol Table Output
--    
--    #### Global Scope (Depth 0)
--    - **test1**
--      - **Entry Type:** PROCEDURE  
--      - **Local Size:** 18  
--      - **Parameters:** None
--    
--    #### Local Scope for Procedure test1 (Depth 1)
--    
--    | Lexeme | Entry Type | Data Type | Size | Offset/Value | Other Info |
--    | ------ | ---------- | --------- | ---- | ------------ | ---------- |
--    | a      | VARIABLE   | REAL      | 4    | 0            |            |
--    | b      | VARIABLE   | REAL      | 4    | 4            |            |
--    | c      | VARIABLE   | REAL      | 4    | 8            |            |
--    | x      | VARIABLE   | INT       | 2    | 12           |            |
--    | y      | VARIABLE   | INT       | 2    | 14           |            |
--    | z      | VARIABLE   | INT       | 2    | 16           |            |
--    
--    ---
--    
--    ### Verification
--    
--    - **Procedure "test1" at Depth 0:**
--      - The procedure is correctly recognized and its local (nested) scope is processed.
--      - Its local size (the sum of all offsets for variables declared in its body) is 18.
--    
--    - **Variables at Depth 1:**
--      - `a, b, c` of type REAL (4 bytes each) are assigned offsets 0, 4, and 8, respectively.
--      - `x, y, z` of type INTEGER (2 bytes each) follow at offsets 12, 14, and 16.
--    
--    This exactly matches the calculation:
--    - After real declarations: offset = 0 + 4 + 4 + 4 = 12.
--    - After integer declarations: 12 + 2 + 2 + 2 = 18.
--    